project_name: 'candle-server'

before:
  hooks:
    - go mod tidy

builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    ldflags: -s -w

archives:
  -
    format: binary
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: 'checksums.txt'

changelog:
  skip: true

snapshot:
  name_template: "{{ .Tag }}-next"

