name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      -
        name: package
        uses: MontyD/package-json-updated-action@master
        id: package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      -
        name: checkout
        uses: actions/checkout@v2
        if: steps.package.outputs.has-updated

      -
        name: fetch
        run: git fetch --prune --unshallow
        if: steps.package.outputs.has-updated

      -
        name: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_OWN_TOKEN }}
        with:
          tag_name: ${{ steps.package.outputs.current-package-version }}
          release_name: ${{ steps.package.outputs.current-package-version }}
          draft: false
          prerelease: false
        if: steps.package.outputs.has-updated

